version: '3.8'
services:
  idm_service:
    build:
      context: ./components/idm_component
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mariadb_users
      - redis

  patient_service:
    build:
      context: ./components/patient_component
      dockerfile: Dockerfileb
    ports:
      - "8002:8002"
    depends_on:
      -mariadb_data

  doctor_service:
    build:
      context: ./components/doctor_component
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mariadb_data

  appointment_service:
    build:
      context: ./components/appointment_component
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    depends_on:
      - mariadb_data

  consultation_service:
    build:
      context: ./components/consultation_component
      dockerfile: Dockerfile
    ports:
      - "8005:8005"
    depends_on:
      - mongodb

  mariadb_users:
    image: mariadb:latest
    volumes:
      - ${MARIADB_USERS_STORAGE}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_USERS_ROOT_PASSWORD}
      MYSQL_DATABASE: "users_db"
    ports:
      - "3306:3306"

  mariadb_data:
    image: mariadb:latest
    volumes:
      - ${MARIADB_DATA_STORAGE}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_DATA_ROOT_PASSWORD}
      MYSQL_DATABASE: "data_db"
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    volumes:
      - ${MONGODB_CONSULTATION_STORAGE}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_CONSULTATION_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_CONSULTATION_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

      