version: '3.8'
services:
  # idm_service:
  #   build:
  #     context: ./idm_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"
  #   depends_on:
  #     - mariadb_users
  #     - redis

  hospital_service:
    build:
      context: ./hospital_service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"

  # consultation_service:
  #   build:
  #     context: ./consultation_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8005:8005"
  #   depends_on:
  #     - mongodb

  # mariadb_users:
  #   image: mariadb:latest
  #   volumes:
  #     - ${MARIADB_USERS_STORAGE}:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MARIADB_USERS_ROOT_PASSWORD}
  #     MYSQL_DATABASE: "users_db"
  #   ports:
  #     - "3307:3306"

  mariadb_hospital:
    image: mariadb:latest
    volumes:
      - ${MARIADB_HOSPITAL_STORAGE}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_HOSPITAL_ROOT_PASSWORD}
      MYSQL_DATABASE: "hospital_db"
    ports:
      - "3308:3306"

  # mongodb:
  #   image: mongo:latest
  #   volumes:
  #     - ${MONGODB_CONSULTATION_STORAGE}:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGODB_CONSULTATION_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_CONSULTATION_ROOT_PASSWORD}
  #   ports:
  #     - "27017:27017"

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
