# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import idm_service_pb2 as idm__service__pb2


class IDMServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/idm.IDMService/Login',
                request_serializer=idm__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=idm__service__pb2.LoginResponse.FromString,
                )
        self.Register = channel.unary_unary(
                '/idm.IDMService/Register',
                request_serializer=idm__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=idm__service__pb2.RegisterResponse.FromString,
                )
        self.GetUser = channel.unary_unary(
                '/idm.IDMService/GetUser',
                request_serializer=idm__service__pb2.GetUserRequest.SerializeToString,
                response_deserializer=idm__service__pb2.UserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/idm.IDMService/UpdateUser',
                request_serializer=idm__service__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=idm__service__pb2.UserResponse.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/idm.IDMService/DeleteUser',
                request_serializer=idm__service__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=idm__service__pb2.DeleteUserResponse.FromString,
                )


class IDMServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IDMServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=idm__service__pb2.LoginRequest.FromString,
                    response_serializer=idm__service__pb2.LoginResponse.SerializeToString,
            ),
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=idm__service__pb2.RegisterRequest.FromString,
                    response_serializer=idm__service__pb2.RegisterResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=idm__service__pb2.GetUserRequest.FromString,
                    response_serializer=idm__service__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=idm__service__pb2.UpdateUserRequest.FromString,
                    response_serializer=idm__service__pb2.UserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=idm__service__pb2.DeleteUserRequest.FromString,
                    response_serializer=idm__service__pb2.DeleteUserResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'idm.IDMService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IDMService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.IDMService/Login',
            idm__service__pb2.LoginRequest.SerializeToString,
            idm__service__pb2.LoginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.IDMService/Register',
            idm__service__pb2.RegisterRequest.SerializeToString,
            idm__service__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.IDMService/GetUser',
            idm__service__pb2.GetUserRequest.SerializeToString,
            idm__service__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.IDMService/UpdateUser',
            idm__service__pb2.UpdateUserRequest.SerializeToString,
            idm__service__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/idm.IDMService/DeleteUser',
            idm__service__pb2.DeleteUserRequest.SerializeToString,
            idm__service__pb2.DeleteUserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
