import secrets
SECRET_KEY = secrets.token_urlsafe(32)
MONGODB_CONSULTATION_ROOT_USERNAME="root"
MONGODB_CONSULTATION_ROOT_PASSWORD=123456789
MONGODB_CONSULTATION_DB_NAME = "consulations"
MONGODB_CONSULTATION_HOST = "mongodb_consulations"
MONGODB_CONSULTATION_PORT = "27017"
MONGODB_URI = f"mongodb://{MONGODB_CONSULTATION_ROOT_USERNAME}:{MONGODB_CONSULTATION_ROOT_PASSWORD}@{MONGODB_CONSULTATION_HOST}:{MONGODB_CONSULTATION_PORT}/{MONGODB_CONSULTATION_DB_NAME}"
ACCESS_TOKEN_EXPIRE_MINUTES = 30
